version: '3.9'

services:

    phmoney_azure:
        build: ./nginx
        image: phalouvas/phmoney_app:0.0.1
        hostname: azure
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}azure.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}azure.rule=Host(`${COMPOSE_PROJECT_NAME}_azure.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}azure.service=${COMPOSE_PROJECT_NAME}azure"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}azure.loadbalancer.server.port=80"
        environment:
            - PHMONEY_ENV=azure

    phmoney_local:
        container_name: ${COMPOSE_PROJECT_NAME}_local
        build: ./nginx
        image: phalouvas/phmoney_app:local
        hostname: local
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}local.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}local.rule=Host(`${COMPOSE_PROJECT_NAME}_local.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}local.service=${COMPOSE_PROJECT_NAME}local"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}local.loadbalancer.server.port=80"
        environment:
            - PHMONEY_ENV=local
        volumes:
            - ../phmoney_app/:/var/www/html/phmoney_app//:rw

    phmoney_assets:
        container_name: ${COMPOSE_PROJECT_NAME}_assets
        build: ./assets
        hostname: assets
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}assets.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}assets.rule=Host(`${COMPOSE_PROJECT_NAME}_assets.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}assets.service=${COMPOSE_PROJECT_NAME}assets"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}assets.loadbalancer.server.port=80"
        volumes:
            - ../phmoney_assets/dist/:/var/www/html/:rw

networks:
    default:
        name: ${COMPOSE_NETWORK_NAME}-local-net
        driver: bridge
